services:
  db:
    container_name: dev-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    networks:
      - livinhome
  minio:
    image: minio/minio:latest
    hostname: 'localhost'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./.data/minio:/data
      - ./.data/minio/config:/root/.minio
    networks:
      - livinhome

networks:
  livinhome:
